-- MySQL Script generated by MySQL Workbench
-- Mon 29 Dec 2014 05:56:29 PM BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Pessoa` (
  `cdPessoa` INT NOT NULL AUTO_INCREMENT,
  `nmPessoa` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `dtInsercaoPessoa` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sexo` VARCHAR(1) NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `email` VARCHAR(100) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`cdPessoa`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`TB_Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Cidade` (
  `cdCidade` INT NOT NULL AUTO_INCREMENT,
  `nmCidade` VARCHAR(50) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`cdCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Bairro` (
  `cdBairro` INT NOT NULL AUTO_INCREMENT,
  `cdCidade` INT NOT NULL,
  `nmBairro` VARCHAR(50) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`cdBairro`),
  INDEX `fk_TB_Bairro_TB_Cidade1_idx` (`cdCidade` ASC),
  CONSTRAINT `fk_TB_Bairro_TB_Cidade1`
    FOREIGN KEY (`cdCidade`)
    REFERENCES `mydb`.`TB_Cidade` (`cdCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Cliente` (
  `cdPessoa` INT NOT NULL,
  `cdBairro` INT NOT NULL,
  `ruaCliente` VARCHAR(45) NOT NULL,
  `nEndCliente` INT NOT NULL,
  `complementoEndCliente` VARCHAR(45) NULL,
  `medicamentos` TEXT NULL,
  INDEX `fk_TB_Cliente_TB_Pessoa1_idx` (`cdPessoa` ASC),
  PRIMARY KEY (`cdPessoa`),
  INDEX `fk_TB_Cliente_TB_Bairro1_idx` (`cdBairro` ASC),
  CONSTRAINT `fk_TB_Cliente_TB_Pessoa1`
    FOREIGN KEY (`cdPessoa`)
    REFERENCES `mydb`.`TB_Pessoa` (`cdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Cliente_TB_Bairro1`
    FOREIGN KEY (`cdBairro`)
    REFERENCES `mydb`.`TB_Bairro` (`cdBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Medico` (
  `cdPessoa` INT NOT NULL,
  `crm` VARCHAR(11) NOT NULL,
  INDEX `fk_TB_Medico_TB_Pessoa1_idx` (`cdPessoa` ASC),
  PRIMARY KEY (`cdPessoa`),
  CONSTRAINT `fk_TB_Medico_TB_Pessoa1`
    FOREIGN KEY (`cdPessoa`)
    REFERENCES `mydb`.`TB_Pessoa` (`cdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Funcionario` (
  `cdPessoa` INT NOT NULL,
  `registroFuncional` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  INDEX `fk_TB_Funcionario_TB_Pessoa_idx` (`cdPessoa` ASC),
  PRIMARY KEY (`cdPessoa`),
  CONSTRAINT `fk_TB_Funcionario_TB_Pessoa`
    FOREIGN KEY (`cdPessoa`)
    REFERENCES `mydb`.`TB_Pessoa` (`cdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_TipoExame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_TipoExame` (
  `cdTipoExame` INT NOT NULL AUTO_INCREMENT,
  `nmTipoExame` VARCHAR(50) NOT NULL,
  `coletaDomicilio` TINYINT(1) NOT NULL,
  `requisitos` TEXT NOT NULL,
  `informacoes` TEXT NULL,
  `preco` FLOAT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`cdTipoExame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Convenio` (
  `cdConvenio` INT NOT NULL AUTO_INCREMENT,
  `nmConvenio` VARCHAR(50) NOT NULL,
  `responsavel` VARCHAR(100) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`cdConvenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Exame` (
  `cdExame` INT NOT NULL AUTO_INCREMENT,
  `cdCliente` INT NOT NULL,
  `cdMedico` INT NULL,
  `cdTipoExame` INT NOT NULL,
  `cdConvenio` INT NULL,
  `dtExame` DATE NULL,
  `hrExame` TIME NULL,
  `coletaDom` TINYINT(1) NOT NULL,
  `dtColetaDom` DATETIME NULL,
  `URLExame` VARCHAR(200) NULL,
  INDEX `fk_TB_Cliente_has_TB_Exame_TB_Cliente1_idx` (`cdCliente` ASC),
  INDEX `fk_TB_Cliente_has_TB_Exame_TB_Medico1_idx` (`cdMedico` ASC),
  INDEX `fk_TB_Exame_TB_Convenio1_idx` (`cdConvenio` ASC),
  INDEX `fk_TB_Exame_TB_TipoExame1_idx` (`cdTipoExame` ASC),
  PRIMARY KEY (`cdExame`),
  CONSTRAINT `fk_TB_Cliente_has_TB_Exame_TB_Cliente1`
    FOREIGN KEY (`cdCliente`)
    REFERENCES `mydb`.`TB_Cliente` (`cdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Cliente_has_TB_Exame_TB_Medico1`
    FOREIGN KEY (`cdMedico`)
    REFERENCES `mydb`.`TB_Medico` (`cdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Exame_TB_Convenio1`
    FOREIGN KEY (`cdConvenio`)
    REFERENCES `mydb`.`TB_Convenio` (`cdConvenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Exame_TB_TipoExame1`
    FOREIGN KEY (`cdTipoExame`)
    REFERENCES `mydb`.`TB_TipoExame` (`cdTipoExame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Cliente_has_TB_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Cliente_has_TB_Medico` (
  `cdCliente` INT NOT NULL,
  `cdMedico` INT NOT NULL,
  PRIMARY KEY (`cdCliente`, `cdMedico`),
  INDEX `fk_TB_Cliente_has_TB_Medico_TB_Medico1_idx` (`cdMedico` ASC),
  INDEX `fk_TB_Cliente_has_TB_Medico_TB_Cliente1_idx` (`cdCliente` ASC),
  CONSTRAINT `fk_TB_Cliente_has_TB_Medico_TB_Cliente1`
    FOREIGN KEY (`cdCliente`)
    REFERENCES `mydb`.`TB_Cliente` (`cdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Cliente_has_TB_Medico_TB_Medico1`
    FOREIGN KEY (`cdMedico`)
    REFERENCES `mydb`.`TB_Medico` (`cdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `cdAdmin` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cdAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horarios` (
  `cdHorarios` INT NOT NULL,
  `horario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cdHorarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
